const express = require('express')
const router = require('./router')
const cors = require('cors')
const tasksRouter = require('./routes/tasksRouter')
const signUpRouter = require('./routes/signupRouter')
const profileInfoRouter = require('./routes/profileinfoRouter')
const profileCardsRouter = require('./routes/profilecardsRouter')
const createTopicRouter = require('./routes/createtopicRouter')
const signinRouter = require('./routes/signinRouter')
const commentRouter = require('./routes/commentRouter')
const cardRouter = require('./routes/cardsRouter')
const app = express()
const uploadfile = require('express-fileupload')

app.use(cors())
app.use(uploadfile())
app.use(express.json())
app.use('/static', express.static('public'))
app.use(cardRouter)
app.use(signUpRouter)
app.use(router)
app.use(commentRouter)
app.use(tasksRouter)
app.use(signinRouter)
app.use(profileInfoRouter)
app.use(profileCardsRouter)
app.use(createTopicRouter)

module.exports = app
